### ISSUE TITLE
[Question][101-azure-dns-new-zone] How to get the name server domain name?

### ISSUE THREAD

**Issue by bingosummer** [Azure/azure-quickstart-templates#1041]
After create a new zone, I want to output the name server domain names. So I add the following in `azuredeploy.json`.
```
"outputs": {
        "nsdname": {
            "type": "string",
            "value": "[reference(resourceId(resourceGroup().name, 'Microsoft.Network/dnszones/NS', parameters('newZoneName'), '@')).properties.nsRecords[0].nsdname]"
        }   
    }
```
Azure Portal gives me an error as belows.
```
Error submitting the deployment request. Additional details from the underlying API that might be helpful: Deployment template validation failed: 'The resource 'Microsoft.Network/dnszones/azurelovecf.com/NS/@' is not defined in a template.'.
```

I know that 'NS/@' is not defined and it's created automatically by Azure DNS. So, my question is how to get the properties of the resource which is not defined in my template?

Thanks

**Comment by singhkay** [comment]
@jtuliani Can you help with this question?

**Comment by bingosummer** [comment]
@jtuliani 
Could you help give me a guide about how to get the name server domain names?
Thanks

**Comment by jtuliani** [comment]
Right now, the name server names are only available via the child resource for the NS records for the zone.  And since the template engine doesn't know about that resource, I don't think there's a way to get them.
We are planning to expose the name server names as a zone property to address this.  Give us a few weeks and we'll get back to you.

**Comment by bingosummer** [comment]
Thanks @jtuliani 
It really helps to expose the name server names as a zone property.

**Comment by bingosummer** [comment]
@jtuliani 
Any update on this?

**Comment by jtuliani** [comment]
We are adding the name server names as zone properties in our next API update, ETA July.

**Comment by singhkay** [comment]
Thanks @jtuliani, closing

**Comment by jtuliani** [comment]
We have shipped an updated REST API, with api-version 2016-04-01.  This includes nameServers as a property of the dnszones resource.

You won't see nameServers property in the resource schema since it is a read-only property, and the schema today only includes writable properties.  But it is there, as documented in our [REST API documentation](https://msdn.microsoft.com/en-us/library/azure/mt130598.aspx).

Please give it a try and let us know if this resolves this issue for you.

**Comment by tansaku** [comment]
@jtuliani do you know if we access the nameserver through the azure portal?

Will a dokku deployed on azure automatically have a nameserver, or will it need to be configured?

many thanks in advance

**Comment by jtuliani** [comment]
The name servers for any zone in Azure DNS are displayed in the 'Essentials' panel for the zone in the Portal.

**Comment by tansaku** [comment]
thanks @jtuliani - we have four dokku related items on our Azure instance:

* dokkuPublicIP - DNS name: agileventures.eastus.cloudapp.azure.com
* DokkuVM
* dokkuVMNic
* DokkuVNet - DNSServers: Azure provided DNS service

Each of these has an essentials panel, but none mention nameservers.  

What's not clear to me is if we have to create a specific Azure DNS component as discussed in https://docs.microsoft.com/en-us/azure/dns/dns-delegate-domain-azure-dns

the thing is that we have another provider managing our top level domain (agileventures.org) - we'd like to have some subdomains (asyncvoter.agileventures.org) use the Azure nameservers, but aren't clear if we have to create a new component, or if the dokku azure instance will have a nameserver by default.

Doing nslookup for the box shows an origin which I thought be our existing nameserver:

```
→ nslookup
> set querytype=soa
> agileventures.eastus.cloudapp.azure.com
Server:		172.20.10.1
Address:	172.20.10.1#53

Non-authoritative answer:
*** Can't find agileventures.eastus.cloudapp.azure.com: No answer

Authoritative answers can be found from:
eastus.cloudapp.azure.com
	origin = prd1.azuredns-cloud.net
	mail addr = msnhst.microsoft.com.eastus.cloudapp.azure.com
	serial = 355080
	refresh = 900
	retry = 300
	expire = 604800
	minimum = 60
```
anyhow, apologies for the long post ...

**Comment by jtuliani** [comment]
Thanks, I understand your scenario better now.

Yes, you can create subdomains (e.g. asyncvoter.agileventures.org) in Azure DNS. In Azure DNS, you will see the name servers assigned to this zone. You will then need to go to your parent domain and set up corresponding NS records with the name asyncvoter to point to these name servers. The link you provided should help you understand the process.

From your child domain in Azure DNS, you can then create DNS 'A' records pointing to your service IP address (you should used a reserved IP in this case), or CNAME records pointing to the Azure-provided DNS names for your service endpoints (e.g. agileventures.eastus.cloudapp.azure.com)

**Comment by tansaku** [comment]
thanks @jtuliani - I've set that up:

![new record set](https://www.dropbox.com/s/17otriynk9coepr/Screenshot%202017-05-18%2016.20.22.png?dl=1)

but the dokku instance is managing multiple docker containers on agileventures.eastus.cloudapp.azure.com - 

so I can point staging.asyncvoter.agileventures.org to agileventures.eastus.cloudapp.azure.com, but I want to be able to point develop.asyncvoter.agileventures.org to agileventures.eastus.cloudapp.azure.com as well (since both develop and staging instances are running within dokku behind agileventures.eastus.cloudapp.azure.com), and then dokku be able to work out which docker container to route to.

Are multiple CNAMEs fine?  and I then just configure with the dokku domain command?

Apologies if this is the wrong place to ask - just it's taken a while to track down anyone with experience in both dokku AND azure :-)

**Comment by jtuliani** [comment]
You can have multiple CNAMEs, so long as they have different names. So having one called 'staging' and another called 'develop' should be fine. They can point to the same endpoint, or different endpoints, that makes no difference (but they can each only point to a single DNS name).

Sounds like it should work :)
