### ISSUE TITLE
[Question] How to add insecure registries on Azure Docker Swarm Template

### ISSUE THREAD

**Issue by vinaysangawar** [Azure/azure-quickstart-templates#1190]
I was wondering how I would go about adding the --insecure-registry flag in this template? I am used to editing the /etc/default/docker file and using DOCKER_OPTS to pass in these parameters on Ubuntu, but I do not see that file when SSHd into a swarm manager VM. Is there a place to add my insecure registries within the template configuration? Or would I have to SSH into each manager/node and update a different file then restart the docker daemon for each one?

Thanks!

**Comment by singhkay** [comment]
@ahmetalpbalkan might be able to help with this

**Comment by vinaysangawar** [comment]
Actually just figured it out if anyone else was curious! You simply add the properties in the options section of the DockerExtension part of the template file. See the attached picture. I was able to SSH tunnel, then export DOCKER_HOST=:2375 in my terminal, then do a "docker login myinsecure1.cloudapp.com:9001" and was able to login successfully and download my private images! 

![insecure](https://cloud.githubusercontent.com/assets/8532372/12900207/28c879ac-ce83-11e5-818b-7f9c6825b881.png)

**Comment by singhkay** [comment]
@vinaysangawar Sweet! Thanks for posting the solution. Relevant XKCD http://xkcd.com/979/  :grinning:

**Comment by ahmetalpbalkan** [comment]
@vinaysangawar you are the best kind of user!

Yes, if you use Docker Extension, you can it's `"docker" > "options"` key to specify docker-engine options and if you use `"compose"` key to stand up a `registry` container with compose.yml described in JSON.

Furthermore you can actually use `"protectedSettings"` key in ARM template to pass secrets (such as storage account key) as an environment variable to docker-compose so that your template doesn't store the secret plain-text.

Docs are here if you are curious: https://github.com/Azure/azure-docker-extension/
