### ISSUE TITLE
101-acs-swarm - can't create docker network

### ISSUE THREAD

**Issue by sascha-egerer** [Azure/azure-quickstart-templates#1273]
I've deployed 101-acs-swarm with 1 agent and 1 master.
It's not possible to create a docker network over the swarm master.

```
$ docker network create foo
Error response from daemon: 500 Internal Server Error: failed to parse pool request for address space "GlobalDefault" pool "" subpool "": cannot find address space GlobalDefault (most likely the backing datastore is not configured)
```

**Comment by singhkay** [comment]
Paging @rgardler

**Comment by sascha-egerer** [comment]
Here's the docker documentation link for "docker network create" https://docs.docker.com/engine/reference/commandline/network_create/#network-create

Creating a overlay network is currently not possible.

**Comment by sascha-egerer** [comment]
Anybody working on that issue? @rgardler ?

**Comment by sandyplace** [comment]
without docker overlay networking you are forced to v1 version of compose files which do not work either if you have links for dependent services. you get errors such as "Unable to find a node fulfilling all dependencies: --link=azureuser_redis_1:azure_redis_1". It would be nice if one or the other work as it makes testing swarm in acs difficult.

**Comment by dgilling** [comment]
The Azure template already sets up Consul for master leader and worker node discovery, but seems that the options are missing the appropiate DOCKER_OPTS when the docker daemon is started.

Add below opts to /etc/default/docker to each swarm worker.
(Where 10.0.X.X is the worker's IP under eth0, and 172.16.X.X:8500 is the IP of the master node which is running Consul)

DOCKER_OPTS="--cluster-advertise=10.0.X.X:2375 --cluster-store=consul://172.16.X.X:8500 -H unix:///var/run/docker.sock -H 0.0.0.0:2375"

Of coarse, it would be better to update the ACS template so that stuff like Scaling the VMSS works correctly without having changes made directly to the VM.

**Comment by inf-rno** [comment]
This is an issue even when using a basic compose file of version '2' as it starts off by creating a default overlay network. And as such will not deploy to the swarm cluster. Setting the env vars should be done as part of the template.

I would submit a pull request if I know where to find the template in question. Can someone point me to it?

**Comment by rgardler** [comment]
I believe this is fixed in an upcoming update (due in production soon). I'll leave the issue open so that once we go live with the update people here can test and indicate results on this issue.

**Comment by inf-rno** [comment]
Thanks @rgardler! Are the underlying ARM templates open source so we can fix/tweak/extend the current template? If so, could you please direct me to it?

**Comment by rgardler** [comment]
The templates are open source in the sense that we publish them on GitHub, but they are not open source in the sense that we will necessarily accept patches, while we are in preview. At present we are working with our partners and then dropping templates into the public repo on a periodic basis. The purpose is certainly to gather feedback, but because of the lag between out internal testing and our publication it's hard to accept patches

This will change over time. In the meantime, you can see the latest public version of the templates at https://github.com/anhowe/scratch/tree/master/mesos-marathon-vmss

**Comment by gvilarino** [comment]
@rgardler I think I'm kind of confused since the template I've always followed as _latest stable_ is the [quickstart repo](https://github.com/Azure/azure-quickstart-templates/tree/master/docker-swarm-cluster)'s

Should I use this other one you're linking to?

Also, is there any updates on the network creation issue being solved? I'm having a hard time understanding that from looking at the templates themselves.
