### ISSUE TITLE
SharePoint Subscription / 2019 / 2016 fully configured - User Profile Service

### ISSUE THREAD

**Issue by ashley-w-brazier-cloudm** [Azure/azure-quickstart-templates#14218]
Hi,
I've used the following https://learn.microsoft.com/en-us/samples/azure/azure-quickstart-templates/sharepoint-adfs/ to  deploy SharePoint 2019

https://github.com/Azure/azure-quickstart-templates/tree/master/application-workloads/sharepoint/sharepoint-adfs

However I am having issue with User Profile directory Sync, it's not syncing any users into SharePoint. I have returned the password as mentioned in the known issues.

I can't see any warning or errors in the event logs. 
![Image](https://github.com/user-attachments/assets/d44165eb-7df7-4eb1-9a46-7cfd77822630)
![Image](https://github.com/user-attachments/assets/2501c2e6-80c0-41ca-96e1-795809ef6ea6)
 Am I missing a step?
Many thanks

**Comment by Yvand** [comment]
Hi @ashley-w-brazier-cloudm, in SharePoint 2016 and 2019, the trial enterprise license has already expired, so you must enter your own in the central administration, then run iisreset and restart the SPTimerV4 service on all the servers.
FYI, SharePoint Subscription does not have this issue because the farm is created during the deployment.
I will add this note to the [known issues](https://github.com/Azure/azure-quickstart-templates/tree/master/application-workloads/sharepoint/sharepoint-adfs#known-issues) list with the next update (coming very soon)

**Comment by ashley-w-brazier-cloudm** [comment]
@Yvand thanks for the update and clarification.
