### ISSUE TITLE
201-VM-Domain-Join does not join the domain

### ISSUE THREAD

**Issue by paulieguk** [Azure/azure-quickstart-templates#1534]
[201-vm-domain-join] https://github.com/Azure/azure-quickstart-templates/blob/master/201-vm-domain-join/azuredeploy.json

### Issue Details
I have been trying to use this extension to join a domain.  The domain controller is running on the same VNet as the server I am trying to join and I can join the domain manually with no issues.  The script states all has completed with no issues, however the vm is not domain joined.  All that has happed is the workgroup of the VM has changed to the domain name.

Any ideas please!
Thank you.
Paul

**Comment by paulieguk** [comment]
I have now resolved this.  The user account had a Hyphen "-" in the username.  It seems the extension does not like this.

**Comment by paulieguk** [comment]
I thought I should not have closed this as it still highlights a bug in the Domain Join extension.

**Comment by singhkay** [comment]
@paulieguk This is currently a known issue due to some misconfiguration of the input parameters. There is a new version of the extension under testing that will be released soon that will report the correct errors rather than joining the workgroup instead. 

You can follow this topic to make sure all the input parameters were correct https://github.com/Azure/azure-powershell/issues/1316#issuecomment-167367214
