### ISSUE TITLE
Re-format all Templates in a Agreed Upon JSON Style

### ISSUE THREAD

**Issue by boumenot** [Azure/azure-quickstart-templates#1729]
Not all templates follow an agreed upon JSON style.  Some indent at 2 spaces, some at 4, some cuddle braces instead of breaking across new lines, etc.  When I made a mass edit to add autoUpgradeMinorVersion to every CustomScriptForLinux extension I created a lot of unnecessary noise in the diffs due to a mismatch in style.  

I wrote a script to automate this for me, but it devolved into a lot manual work to minimize the diffs, and ensure only the salient points were in the diff.  I would like to re-write all JSON documents in the repo in an agreed upon style, and then add a commit hook (or build step) to ensure all documents are the same style going forward.  Thoughts?

**Comment by singhkay** [comment]
Interesting idea, one that I can definitely see being very useful to improve readability. Due to the nature of Github layout not being very wide, I've found 2 spaces indent usually works best. 

>  add a commit hook (or build step)

How will this step work? Will this commit to an open PR or create a new PR after the merge?

Adding few others to get their thoughts on this @sedouard @marcvaneijk @gatneil

**Comment by boumenot** [comment]
😄 I don't know how it will work with GitHub.  I'll need to do some research.

**Comment by boumenot** [comment]
I've sent a PR to address this issue (#1737).  I couldn't find a way to add a pre-commit hook in a way that I liked, so I opted to make it an explicit build target.  Developers will need to install NPM and the necessary libraries to use the target.  It does provide a standard and multi-platform way to implement consistent styling, and provides the necessary tooling to apply the agreed upon style.
