### ISSUE TITLE
PS Script & Link Templated

### ISSUE THREAD

**Issue by CraigCloudITPro** [Azure/azure-quickstart-templates#1735]
Hi guys, I've been doing a bit of ARM Template creation for a while now, and i'm just getting into the more advance stuff.

I'm looking at deploying this template through Visual Studio https://github.com/Azure/azure-quickstart-templates/tree/master/active-directory-new-domain 

With the 101 and 201 series i simply copied and pasted the RAW azure.deploy & azure.parameters code into a blank VS template, then edited the parameters and so on after

The one above ^^ includes an additional PowerShell script and two other json templates, how will all these connect to each other? Without sounding stupid? I know i can click the 'Deploy to Azure', but i want to build this all in VS 

Any help is greatly appreciated, thank you

**Comment by singhkay** [comment]
@CraigSCCM In it's current state since the modules live in Github, the URI points to these locations

https://github.com/Azure/azure-quickstart-templates/blob/master/active-directory-new-domain/azuredeploy.json#L132
https://github.com/Azure/azure-quickstart-templates/blob/master/active-directory-new-domain/azuredeploy.json#L165

So you should still be able to deploy this template in VS. However, you'll need to modify the template if you want to host the modules in Azure Storage and specify the storage account keys.

**Comment by CraigSCCM** [comment]
@singhkay thanks for this, how do I incorporate the ADPDC Powershell script ?

**Comment by singhkay** [comment]
@CraigSCCM No need to in the current form. Just copy paste the contents of template and parameters file and deploy from VS. ARM will download the zip files from the Github URIs.

**Comment by CraigSCCM** [comment]
Hi @singhkay i've just done as above, copy and pasted template and parameters file, and nothing else and i got the below error

`InvalidTemplateDeployment: The template 
16:48:18 - [ERROR] deployment 'azuredeploy-0420-1548' is not valid according to the validation 
16:48:18 - [ERROR] procedure. The tracking id is 'adb9d239-07ac-4ff4-a174-c31e6a74704d'`

**Comment by singhkay** [comment]
Make sure you replace the placeholder parameters (GEN-*) in the parameter files to actual values

**Comment by CraigSCCM** [comment]
thanks @singhkay for some reason it keeps erroring on Visual Studio, but i call the json with powershell and it works....very strange :-/
