### ISSUE TITLE
Couchbase-on-ubuntu template having an issue - The template deployment 'Microsoft.Template' is not valid according to the validation procedure. The tracking id is '...'. See inner errors for details. Please see http://aka.ms/arm-deploy for usage details.

### ISSUE THREAD

**Issue by cihanb** [Azure/azure-quickstart-templates#1822]
re: https://github.com/Azure/azure-quickstart-templates/tree/master/couchbase-on-ubuntu

### Issue Details
The template deployment 'Microsoft.Template' is not valid according to the validation procedure. The tracking id is '...'. See inner errors for details. Please see http://aka.ms/arm-deploy for usage details.

### Repro steps (*if necessary, delete otherwise*)
1. Supply new resource group name, new region that matches the region name under template with admin username and password and pick defaults for all other param. 
2. Client create.

The following error appear in the create dialog and deployment fails.
The template deployment 'Microsoft.Template' is not valid according to the validation procedure. The tracking id is '...'. See inner errors for details. Please see http://aka.ms/arm-deploy for usage details.

**Comment by singhkay** [comment]
@cihanb This error is usually from pre-deployment checks to fast fail deployments due to one of the parameter values not being right or subscription not having enough cores in the region. With that said, when I tried deploying it I see the template fail due to storage account name being already taken. The latest guidance to avoid these kinds of errors is to generate a unique storage account name rather than asking the user to input. If you're updating this templates, please see #944 and #966. Also our latest best practices guide is here https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md

**Comment by cihanb** [comment]
ok verified that it is the storage account.  
thanks

**Comment by singhkay** [comment]
@cihanb awesome!

**Comment by mnsameer** [comment]
https://raw.githubusercontent.com/mnsameer/scaling/master/deploy.json getting same error
