### ISSUE TITLE
HTTP(S) interface for "Azure Jenkins" from Marketplace - not accessible

### ISSUE THREAD

**Issue by FrailWords** [Azure/azure-quickstart-templates#3137]
[Azure Jenkins](https://github.com/Azure/azure-quickstart-templates/tree/master/azure-jenkins)

### Issue Details
I've deployed an instance of Linux-VM-based 'Azure Jenkins' instance from the Azure Marketplace.  After deployment, I am able to SSH into the box.

After giving a name for the box under `.westus.cloudapp.azure.com` domain, I tried HTTP(S) access to the Jenkins site but its not accessible.

I did try allowing specific ports (80, 443) on the network interface under the 'inbound rules' as well but that didn't work.

**Comment by EricJizbaMSFT** [comment]
Have you tried going here: http://< your_jenkins_vm_dns >:**8080** ?

The template you linked to defaults 8080 as the port. We can add this information to the README to make it more clear for others

**Comment by FrailWords** [comment]
@EricJizbaMSFT **8080** port works 👍 .   Thank you!

**Comment by FrailWords** [comment]
@EricJizbaMSFT One more point that can be added is the 'default admin password' location - 

`sudo cat /var/lib/jenkins/secrets/initialAdminPassword`

**Comment by EricJizbaMSFT** [comment]
@FrailWords FYI we have updated our guidance on this. Because Jenkins uses 'http' by default, we actually recommend users create an ssh tunnel for port 8080 and view the dashboard at http://localhost:8080/ on their local machine.

We only recommend you allow port 8080 in your network security group if you also setup 'https' traffic. Of course if you are just trying it out and care more about convenience than security, that is totally up to you.
