### ISSUE TITLE
Resource plan can not be changed.

### ISSUE THREAD

**Issue by ljt91** [Azure/azure-quickstart-templates#3172]
oms-all-deploy
https://github.com/Azure/azure-quickstart-templates/tree/master/oms-all-deploy

### Issue Details
Error: Code=CannotUpdatePlan; Message=Resource plan can not be changed.

### Repro steps (*if necessary, delete otherwise*)
1. Re-running the template over an existing configuration with the Solutions in place.
Initial deployment works but when running again the follow error throws.

**Comment by krnese** [comment]
Thanks. The APIs are in preview (solution + operationalInsights), so you might see this error when you re-run the deployment.

**Comment by krnese** [comment]
Hey Lyon - this should now be fixed. Please give it a spin if you can :-) 👍

**Comment by rosieks** [comment]
Is it broken again? I still have such error

**Comment by alexmarshall132** [comment]
I'm getting this error as well when trying to release my custom solution from an ARM template

**Comment by fepere** [comment]
Hi Guys, it´s broken again ? can you try to validate or help me here ?

**Comment by sudmis** [comment]
I am still facing this issue, how can we fix it

**Comment by spbreed** [comment]
It's been an year, still idempotency is breaking. Can't redeploy the template. Could someone from MS look in to this?

**Comment by fepere** [comment]
Hi @spbreed 
you need to validate the arm template to remove the issues, on my case I had the update the solutions to match the existing name of the OMS solutions and then the template was fine without any failures.

**Comment by jurjenoskam** [comment]
Hi @spbreed and @sudmis, I ran into this issue as well and for me the problem was that at first deployment of the template, the plan name specified in the template for the resource type Microsoft.OperationsManagement/solutions apparently did not end up to be the plan name of to the resource that was actually deployed. (You can see this in the portal when you view the Overview screen of the "Solution" resource: on the top right (under the "Solution" header) the plan name is shown. In my case, this was different from the plan name that I had specified in my template.)

When re-deploying the template, this difference caused validation to fail with a "can't update plan" error.

The fix (workaround?) is to make sure that the "name" of the resource is the same as the "name" of the plan, as shown in this fragment:

```json
        {
            "apiVersion": "2015-11-01-preview",
            "type": "Microsoft.OperationsManagement/solutions",
            "location": "[variables('workspaceLocation')]",
            "name": "[concat(variables('workspaceName'), '-containerinsights')]",
            "properties": {
                "workspaceResourceId": "[resourceId('Microsoft.OperationalInsights/workspaces/', variables('workspaceName'))]"
            },
            "plan": {
                "name": "[concat(variables('workspaceName'), '-containerinsights')]",
                "product": "OMSGallery/ContainerInsights",
                "promotionCode": "",
                "publisher": "Microsoft"
            },
            "dependsOn": [
                "[concat('Microsoft.OperationalInsights/workspaces/', variables('workspaceName'))]"
            ]
        }
```

After making this change, my template worked as expected, including idempotency.

**Comment by arjunkakkar93** [comment]
Still facing the same issue even after making sure the name of the plan and the resource in the template is the same

**Comment by pchettri3** [comment]
I am getting same error on bicep deployment for ### 
{"code":"CannotUpdatePlan","message":"Resource plan can not be changed for Resource id: '/subscriptions/resourceGroups/neuCoreRG01/providers/Microsoft.OperationsManagement/solutions/AzureActivity(laWsharedserviclog)'"}

Tried with the inline script to get the same error -
Existor Not
[if(parameters('linkedResourceExists'), 'existing', 'new')]
