### ISSUE TITLE
[windows-puppet-agent] Cannot validate argument on 'Thumbprint'

### ISSUE THREAD

**Issue by kenazk** [Azure/azure-quickstart-templates#702]
I'm seeing an error in the Extension Handler when I'm creating a Windows server with Puppet Agent installed: 

`PSMessageDetails      : 
Exception             : System.Management.Automation.ParameterBindingValidationE
                        xception: Cannot validate argument on parameter 
                        'Thumbprint'. The argument is null or empty. Provide an 
                        argument that is not null or empty, and then try the 
                        command again. ---> System.Management.Automation.Validat
                        ionMetadataException: The argument is null or empty. 
                        Provide an argument that is not null or empty, and then 
                        try the command again.
`

Do you know what this might be caused by? 

Also, I think you also need to pass the following 
`"PUPPET_AGENT_CERTNAME":"[parameters('puppetAgentVMName')]"`

In the properties section.

**Comment by ahmetalpbalkan** [comment]
@kenazk not sure why this is assigned to me?

**Comment by kenazk** [comment]
Sorry Ahmet. Thought you were the author. Reassigned to Kundana.

**Comment by singhkay** [comment]
@KundanaP Any update on this?

**Comment by sebbrochet** [comment]
As of 2016-03-14, I'm still experiencing this error while installing the PuppetLabs 3.2 extension on a Windows Server 2012 R2 VM on Azure. I should add that this node has been previously configured to allow WinRM using HTTPS with a self-signed certification (based on this [PS script](https://github.com/sebbrochet/azure_win/blob/master/vm_creation/ConfigureRemotingForAnsible.ps1)). Would it be an incompatibility with such configured WinRM endpoint? 

I had to manually start the Puppet Agent in order to finish the *bootstrap* process of my windows node. BTW, I've also had to install .NET Framework **3.5** (while **4.5** version was already installed) in order to make it happy.
