### ISSUE TITLE
Virtual Networks - subnet, delegation array

### ISSUE THREAD

**Issue by roofiq** [Azure/azure-quickstart-templates#7541]
Hello,

I'm working on ARM template creating VNet with subnet and all the components.
[Subnets arm template](https://docs.microsoft.com/en-us/azure/templates/microsoft.network/virtualnetworks/subnets)

Why "delegations" is an array? There can't be more delegation than one, right? It has to be one service for subnet.

Thanks,
Rafal

**Comment by bmoore-msft** [comment]
Not 100% certain but I suspect it's either possible to have more than one (though I agree it seems odd) or they are allowing for future expansion without a breaking change.  You could post a question in the docs and should be able to get a more definitive answer.

Since this isn't really a QuickStart issue I'm going to close out the issue.
