### ISSUE TITLE
Easily deployable Docker Hub/Registry

### ISSUE THREAD

**Issue by bbirand** [Azure/azure-quickstart-templates#833]
This in my opinion is sorely missing from the Azure suite. Docker Hub and Quay are both extremely slow. I believe deploying a single node that's already install and configured to host Docker Images would be very valuable. Somewhat like Amazon ECR (https://aws.amazon.com/ecr/)

**Comment by singhkay** [comment]
Adding few folks who are working on Azure container service to take a look at this request @rgardler @ahmetalpbalkan @anhowe

**Comment by ahmetalpbalkan** [comment]
@bbirand can you please take a look at https://azure.microsoft.com/en-us/documentation/articles/virtual-machines-docker-registry-on-azure-blob-storage/ ? This document contains a container definition to start a registry that stores files on Azure Blob Storage. You can easily convert this to an ARM template using [Docker Extension](https://github.com/Azure/azure-docker-extension).

I thought about creating a template for this, however it just seems like running the `docker run registry` command in your setup is easier since having a low-traffic single registry container in a VM and not having auth set up for you does not really seem beneficial or cost-effective.

Alternatively if you are looking for an enterprise-grade solution such as GCR/ECR, we have Docker Trusted Registry offering in Azure Marketplace (portal.azure.com).

**Comment by bbirand** [comment]
Hi @ahmetalpbalkan , thanks for the reply!

I had read that document. Loading up a Docker image is easy enough, but then securing the server is getting a bit more annoying. After going through many steps on the Docker documentation, I realized I'm spending way more time setting a standalone registry on one machine than I did setting up a 5 node mesos cluster and a jumpbox. I still think there would be benefit in having a simple one-click template to fire it up.

Also, I'm of the opinion that running a Docker registry on the same Docker engine that is running production containers would be a bad idea. I'd feel much more comfortable running the registry on its own, regardless of the cost implications. 

Ideally, I wished Azure also had a service similar to GCR/ECR, so I wouldn't worry about any VMs. Looking at the pricing difference between Docker Trusted Registry in the Marketplace and ECR is instructive. But I think I read somewhere that that was in the pipeline.

Feel free to close this issue.
